### PR TITLE
Improve Box IOU

### PR DESCRIPTION
**Pull request by Compaile**
avoid double calculations, add early return (if O3 doesnt pick this up by itself)

### CODE REVIEW

**Comment by suminoshi** [comment]
box_giou,diou,test_dunion
box_iou is also referenced from the above three places.
I don't think it can be built as is.

**Comment by Compaile** [comment]
Why not? its just an overloaded second version for  box_union.  The non overloaded version still can be called as before

**Comment by Compaile** [comment]
image
i think the git commit view is a bit buggy/missleading. if you look at the file directly thats how those are implemented

**Comment by stephanecharette** [comment]
Thanks again for the PR.

**Pull request merged**
